[build]
builder = "nixpacks"

[deploy]
startCommand = "npx prisma db push --skip-generate && next start -p ${PORT:-3000}"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
