[build]
builder = "nixpacks"

[deploy]
startCommand = "prisma db push --accept-data-loss && next start -H 0.0.0.0 -p ${PORT:-3000}"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
